spring.application.name=msa-01-client
server.port=8081

spring.config.import=optional:configserver:http://localhost:8080
spring.properties.active=prod
spring.cloud.config.fail-fast=true
spring.cloud.config.enabled=true
