# spring.application.name должно быть такое, какую конфигурацию у сервера запрашиваем, и в репозитории имя конфигов такое же
# здесь: config-client-prod.properties и config-client-dev.properties
spring.application.name=config-client
server.port=8081

spring.config.import=optional:configserver:http://localhost:8080
spring.profiles.active=prod
spring.cloud.config.fail-fast=true
spring.cloud.config.enabled=true
